### ISSUE TITLE
Тест

### ISSUE THREAD

**Issue by Fodense** [pashpashovich/gradleTask#1]
Тест должен отвечать за одно действие, а не за всё что только можно)

Лучшим решение в данном случае было бы разделить этот тест на два: положительные кейсы и отрицательные при этом используя @ParameterizedTest

https://github.com/pashpashovich/gradleTask/blob/d28ccadbb0750ac692d06c936a1d8937b0c07020/core/src/test/java/AllPositiveNumbersTest.java#L8

**Comment by pashpashovich** [comment]
Понял) Исправил и запушил новый вариант с @ParameterizedTest
